"""create demos and steps tables

Revision ID: 03b6f8c3c6ab
Revises: 
Create Date: 2026-05-20 12:14:48.262098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03b6f8c3c6ab'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('demos',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the demo'),
    sa.Column('title', sa.String(), nullable=True, comment='Title or name of the demonstration'),
    sa.Column('status', sa.String(), nullable=False, comment='Processing status: processing, completed, failed'),
    sa.Column('video_url', sa.String(), nullable=True, comment='URL to the uploaded video file (S3 or local storage)'),
    sa.Column('duration', sa.Integer(), nullable=True, comment='Video duration in seconds'),
    sa.Column('language', sa.String(), nullable=False, comment="Language code for the demonstration (e.g., 'en', 'es', 'fr')"),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Timestamp when the demo was created'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_demos_id'), 'demos', ['id'], unique=False)
    op.create_table('steps',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the step'),
    sa.Column('demo_id', sa.UUID(), nullable=False, comment='Reference to the parent demo'),
    sa.Column('step_number', sa.Integer(), nullable=False, comment='Sequential number of this step within the demo'),
    sa.Column('action', sa.String(), nullable=True, comment='Type of action performed (e.g., click, scroll, type, hover)'),
    sa.Column('element', sa.String(), nullable=True, comment='Target element or component for the action'),
    sa.Column('coord_x', sa.Float(), nullable=True, comment='X-coordinate of the action on the screen'),
    sa.Column('coord_y', sa.Float(), nullable=True, comment='Y-coordinate of the action on the screen'),
    sa.Column('image_url', sa.String(), nullable=True, comment='URL to the screenshot image for this step (S3 or local storage)'),
    sa.Column('ai_description_en', sa.Text(), nullable=True, comment='AI-generated description of the step in English'),
    sa.Column('ai_description_ar', sa.Text(), nullable=True, comment='AI-generated description of the step in Arabic'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Timestamp when the step was created'),
    sa.ForeignKeyConstraint(['demo_id'], ['demos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_steps_demo_id'), 'steps', ['demo_id'], unique=False)
    op.create_index(op.f('ix_steps_id'), 'steps', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_steps_id'), table_name='steps')
    op.drop_index(op.f('ix_steps_demo_id'), table_name='steps')
    op.drop_table('steps')
    op.drop_index(op.f('ix_demos_id'), table_name='demos')
    op.drop_table('demos')
    # ### end Alembic commands ###
